[package]
name = "rusty-chess-cli"
version = "0.1.0"
edition = "2021"
description = "Simple command line chess game written in Rust"

[dependencies]
rusty-chess-core = { path = "../core" }
regex = "1.5.5"
lazy_static = "1.4.0"

